name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  image_scan:
    name: test
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.2
   # - name: setup docker
   #   uses: docker-practice/actions-setup-docker@v1
    - name:  build image
      run: docker build -f Dockerfile -t myapp:test .
    - name: scan image
      uses: docker/scout-action@v1.6.4
